/**
 * Every string the user reads lives here, so wording is easy to change.
 * Keep the tone of the design canvas: plain, warm, short. Sentence case for
 * body copy; the display face does its own uppercasing.
 */

export const copy = {
  dock: {
    /** e.g. "UP NEXT · AFTER LUNCH" — the display face uppercases it anyway. */
    upNextAnchor: (anchor: string) => `Up next · ${anchor}`,
    upNextTime: (time: string) => `Up next · ${time}`,
    upNextAnytime: 'Up next · anytime today',
    /** e.g. "Lunch Loop · 1 of 3 done today" */
    crewProgress: (crew: string, done: number, total: number) =>
      `${crew} · ${done} of ${total} done today`,
    soloProgress: (done: number, total: number) =>
      `${done} of ${total} done today`,
    allDone: 'All done today. Nice stack.',
    checkInLabel: (habit: string) => `Check in: ${habit}`,
    checkedInLabel: (habit: string) => `Checked in: ${habit}`,
    tabs: {
      today: 'Today',
      myDay: 'My Day',
      crews: 'Crews',
      progress: 'Progress',
      you: 'You',
    },
  },

  today: {
    doneCount: 'Done',
    upNext: 'Up next',
    allCrews: 'All crews',
    checkIn: 'Check in',
    checkedIn: 'Checked in',
    checkInLabel: (habit: string) => `Check in: ${habit}`,
    undoCheckIn: 'Undo check-in',
    undo: '\u00b7 Undo',
    editLabel: (habit: string) => `Edit ${habit}`,
    anytime: 'Anytime today',
    done: 'Done',
    open: 'Not yet',
    streakDays: (days: number) => `${days} day${days === 1 ? '' : 's'}`,
    allDone: 'Everything done today. Nice stack.',
    upNextLabel: 'Next up',
    everything: 'Everything today',
    missed: 'Missed',
    later: 'Later',
    doneTag: 'Done',
    nothingLeft: 'Nothing left today.',
    anytimeShort: 'Anytime',
    emptyTitle: 'Nothing stacked yet',
    emptyBody: 'Add your first habit and it will show up here, hanging off a moment you already have.',
    addHabit: 'Add a habit',
    newHabit: 'New habit',
    backToToday: 'Back to today',
    viewingPast: 'You can still check in on a day you missed.',
    loadFailed: 'Could not load today. Pull down to try again.',
  },

  auth: {
    title: 'Build habits\nwith your\npeople.',
    blurb:
      'Stack new habits onto the routine you already have. Do them with friends who notice when you don\u2019t.',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    sendLink: 'Send me a link',
    sending: 'Sending\u2026',
    linkSent: (email: string) =>
      `Check ${email} \u2014 the link signs you straight in. It lasts an hour.`,
    useAnotherEmail: 'Use a different email',
    appleHint: 'Sign in with Apple needs a development build; it does not work in Expo Go.',
    invalidEmail: 'That does not look like an email address.',
    genericError: 'Something went wrong. Try again in a moment.',
    notConfigured:
      'Supabase is not connected yet. Add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY to .env.local, then restart the dev server.',
    signingIn: 'Signing you in\u2026',
    linkExpired: 'That link has already been used, or it expired. Ask for a new one.',
    signOut: 'Sign out',
  },

  onboarding: {
    back: 'Back',
    skip: 'Skip',
    progress: (step: number, total: number) => `Step ${step} of ${total}`,

    routine: {
      eyebrow: 'Step 1 · Your routine',
      title: 'What does your\nday look like?',
      blurb: 'These are the moments your habits will stack onto. Rough times are fine.',
      addOwn: 'Your own',
      ownPlaceholder: 'Name this moment',
      timeLabel: (label: string) => `Change the time for ${label}`,
      removeLabel: (label: string) => `Remove ${label}`,
      next: 'Looks right',
      saving: 'Saving\u2026',
      failed: 'Could not save your routine. Try again.',
      pickTime: 'Pick a time',
      done: 'Done',
    },

    habit: {
      eyebrow: 'Step 2 · First habit',
      title: 'Start with\none.',
      blurb: 'Small beats ambitious. We matched each one to a moment in your day.',
      after: (anchor: string) => `After ${anchor}`,
      makeOwn: 'Make my own instead',
      add: (habit: string) => `Add ${habit}`,
      adding: 'Adding\u2026',
      failed: 'Could not add that habit. Try again.',
    },

    crew: {
      eyebrow: 'Step 3 · Your crew',
      title: 'It\u2019s in\nyour day.',
      justYou: 'Just you, for now',
      isNew: 'New',
      pitch: 'People who start with friends are way more likely to follow through',
      pitchBlurb: 'Invite 1\u20134 friends. Each picks their own moment. You all keep one streak.',
      invite: 'Invite friends',
      solo: 'Start solo for now',
      you: 'You',
    },
  },

  newHabit: {
    titleNew: 'New habit',
    titleEdit: 'Edit habit',
    cancel: 'Cancel',
    lands: 'Lands on My Day',
    iWill: 'I will\u2026',
    namePlaceholder: '15 min walk',
    when: 'When',
    modeAfter: 'After ___',
    modeAfterSub: 'Stack it',
    modeAt: 'At a time',
    modeAtSub: 'Set a clock',
    modeAny: 'Anytime',
    modeAnySub: 'No set spot',
    afterYou: 'After you\u2026',
    atTime: 'At',
    whichDays: 'Which days?',
    everyDay: 'Every day',
    weekdays: 'Weekdays',
    weekends: 'Weekends',
    needDay: 'Pick at least one day.',
    dayName: (day: number) =>
      ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][day] ?? '',
    color: 'Colour',
    doItWith: 'Do it with',
    solo: 'Solo',
    crewsLater: 'Crews arrive in a later build step; every habit is solo for now.',
    save: 'Add to my day',
    saveEdit: 'Save changes',
    archive: 'Archive this habit',
    archived: 'Archived. It keeps its history and stops showing up.',
    needName: 'Give it a name first.',
    needAnchor: 'Pick the moment it stacks onto.',
    noAnchors: 'You have no moments yet. Set your routine first.',
    /** The live sentence under the name field. */
    previewAfter: (anchor: string, name: string) => `${anchor} \u2192 ${name}`,
    previewAt: (time: string, name: string) => `${time} \u2192 ${name}`,
    previewAny: (name: string) => `Anytime today \u2192 ${name}`,
  },

  nudge: {
    /** The presets from the brief, in order. */
    presets: ['Walk time!', 'You\u2019re the last one', 'Don\u2019t leave us hanging', 'Streak\u2019s on you'],
    sendTitle: (name: string) => `Nudge ${name}`,
    sendSub: (moment: string, left: number) =>
      `${moment} \u00b7 ${left} left to keep the streak`,
    pick: 'Pick a nudge',
    writeYourOwn: 'Write your own',
    customPlaceholder: 'Say something short',
    rule: 'One nudge per friend per day. It lands at their moment, not before.',
    send: 'Send nudge',
    sent: 'Nudge sent',
    already: 'You have already nudged them today.',
    notAllowed: 'They have checked in already \u2014 nothing to nudge about.',
    nudge: 'Nudge',
    nudged: 'Nudged',
    cancel: 'Cancel',

    /** The received side. */
    inbox: (count: number) => `${count} nudge${count === 1 ? '' : 's'} for you`,
    from: (name: string) => `${name} nudged you`,
    openTitle: (name: string) => `${name}, the streak\u2019s on you.`,
    didIt: 'Did it? Check in',
    headingOut: 'Heading out now',
    onTheWay: (name: string) => `${name}\u2019s on the way`,
    youAreOnTheWay: 'You\u2019re on the way',
    skipToday: 'Skip today',
    streakSaved: 'Streak saved',
    thanks: 'Say thanks',
    thanksForPush: 'Thanks for the push',
    sameTimeTomorrow: 'Same time tmrw',
    thanked: 'Thanks sent',
    pushLater:
      'Push notifications arrive in a later build step; nudges show up in the app for now.',
  },

  invite: {
    title: 'Bring your crew',
    spots: (taken: number) => `${taken} of 5 spots`,
    whatTheyGet: 'What they\u2019ll get',
    share: 'Send invite',
    linkLabel: 'Join the crew',
    copyHint: 'The link works for seven days, or until the crew is full.',
    universalLinksLater:
      'The link needs the Tsumiki domain set up before it opens the app from a browser. Until then, share it with someone who already has the app.',
    full: 'This crew is full.',
    failed: 'Could not make an invite link.',

    joinTitle: (crew: string) => `Join ${crew}`,
    invitedBy: 'You\u2019ve been invited',
    yourMoment: 'You\u2019ll do it after\u2026',
    join: 'Join the crew',
    notNow: 'Not now',
    signInToJoin: 'Sign in to join',
    signInBlurb: 'Make an account first and we\u2019ll bring you straight back here.',
    notFound: 'That invite link has expired, or it never existed.',
    crewFull: 'This crew already has five people in it.',
    alreadyIn: 'You\u2019re already in this crew.',

    joinedTitle: 'You\u2019re in.',
    joinedBody: (crew: string, count: number) =>
      `${crew} is ${count} strong. Everyone can see you joined.`,
    firstCheckIn: 'First check-in',
    seeMyDay: 'See my day',
  },

  crews: {
    title: 'Crews',
    groupStreak: 'Group streak',
    best: (days: number) => `Best: ${days}`,
    daysStrong: (days: number) => (days === 1 ? 'Day strong' : 'Days strong'),
    startToday: 'Start it today',
    sameHabit: (habit: string) => `${habit}. Same habit, everyone\u2019s own anchor.`,
    crewLine: (inCount: number, total: number) => `Crew \u00b7 ${inCount} of ${total} in`,
    spots: (count: number) => `${count}/5 crew`,
    memberIn: 'In',
    memberNotYet: 'Not yet',
    you: 'You',
    checkIn: 'Check in',
    checkedIn: 'Checked in',
    graceUsed: 'One miss, back tomorrow keeps it alive',
    leave: 'Leave this crew',
    back: 'Back',
    invite: 'Invite',
    nudgesLater: 'Nudging arrives in a later build step.',

    emptyTitle: 'No crews yet',
    emptyBody:
      'A crew is 2 to 5 people doing the same habit, each at their own moment, sharing one streak.',
    startCrew: 'Start a crew',
    pickHabit: 'Which habit?',
    noSoloHabits: 'Every habit you have is already in a crew. Add another one first.',
    nameIt: 'Name the crew',
    namePlaceholder: 'Lunch Loop',
    create: 'Create crew',
    needName: 'Give the crew a name.',
    cancel: 'Cancel',
  },

  schedule: {
    title: 'Your day',
    blurb:
      'The moments your habits stack onto. Give one an end time and it becomes a block, so the gaps around it are real.',
    add: 'Add a moment',
    label: 'What is it?',
    labelPlaceholder: 'Work',
    starts: 'Starts',
    ends: 'Ends',
    lasts: 'It lasts a while',
    lastsHint: 'A block like a work day or a school run.',
    noEnd: 'Just a moment',
    save: 'Save',
    delete: 'Remove',
    deleteHint: 'Habits stacked on it keep going; they just need a new moment.',
    needLabel: 'Give it a name.',
    needLaterEnd: 'It has to end after it starts.',
    empty: 'Nothing in your day yet.',
    done: 'Done',
    /** e.g. "9:00 – 5:30 pm" */
    range: (start: string, end: string) => `${start} \u2013 ${end}`,
  },

  stats: {
    title: 'Progress',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    today: 'Today',
    thisWeek: 'This week',
    thisMonth: 'This month',
    earlier: 'Earlier',
    later: 'Later',
    doneOf: (done: number, due: number) => `${done} of ${due} due`,
    covering: (from: string, to: string) => `${from} \u2013 ${to}`,
    noneDue: 'Nothing was due yet in this window.',
    empty: 'Once you have checked a habit in, this fills up.',
    run: 'Run',
    best: 'Best',
    rate: 'Done',
    notDue: 'Grey days were never due.',
    nothingHere: 'Nothing was due in this period.',
    notYet: 'Not due yet',
    resetTitle: 'Reset your history',
    resetBody:
      'Deletes every check-in you have ever made. Your habits, routine and crews stay. There is no undo.',
    reset: 'Reset history',
    resetConfirm: 'Yes, delete every check-in',
    cancel: 'Cancel',
    storage:
      'Your habits and check-ins live in your Tsumiki account, not on this phone. Deleting the app signs you out; everything comes back when you sign in again.',
  },

  myDay: {
    title: 'My day',
    editRoutine: 'Edit routine',
    habitCount: (count: number) => `${count} habit${count === 1 ? '' : 's'}`,
    breakdown: (stacked: number, solo: number) =>
      `${stacked} stacked \u00b7 ${solo} timed`,
    now: 'Now',
    anytime: 'Anytime today',
    freeHours: (hours: number) => `${hours} free hour${hours === 1 ? '' : 's'}`,
    addHabit: 'Add a habit',
    newHabit: 'New habit',
    solo: 'Solo',
    everyDay: 'every day',
    empty: 'Set your routine first and the day will fill in around it.',
    dragHint: 'Hold a habit to move it to another moment.',
    dropOnMoment: (label: string) => `after ${label.toLowerCase()}`,
    dropAtHour: (hour: string) => `at ${hour}`,
    moveFailed: 'Could not move it. Try again.',
  },

  you: {
    notifications: 'Notifications',
    on: 'Reminders and nudges are on for this phone.',
    simulator: 'Push needs a real phone; the simulator cannot receive it.',
    denied: 'Notifications are turned off. Turn them on in Settings to get reminders.',
    noProjectId:
      'Push needs an Expo project id. Run `npx eas init` once, then rebuild the app.',
    failed: 'Could not register this phone for push.',
    expoGo:
      'Expo Go cannot receive push at all \u2014 this needs a development build.',
    enable: 'Turn on notifications',
    turnOff: 'Stop notifications on this phone',
    quietHours: (start: string, end: string) => `Quiet hours ${start} to ${end}`,
    timezone: (zone: string) => `Times follow ${zone}`,
  },

  placeholder: {
    /** Used by the screens that are still scaffolding in build step 1. */
    comingSoon: 'Coming in a later build step.',
    today: 'The hero card, the done count and the up-next row land here.',
    myDay: 'The timeline: anchors, stacked habits, the NOW line and free-time gaps.',
    crews: 'Group streak, the last 7 days, and a tile per member.',
    you: 'Your routine anchors, quiet hours and notification settings.',
  },
} as const;
